version: 2.1
jobs:
  build:
    working_directory: ~/public  
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
