version: 2.1
jobs:
  build:
    working_directory: ~/public  
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install     
      - run:
          name: tests
          command: npm test
      - store_artifacts:
          path: test-results.xml     
          prefix: tests
      - store_artifacts:
          path: coverage    
          prefix: coverage          
      - store_test_results:
          path: test-results.xml
